---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /store/awsrds
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /store/vault
    schedule:
      interval: daily
