linters:
  enable-all: true
  disable:
    - testpackage
    - scopelint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - gochecknoglobals
        - wsl
        - lll
        - funlen


run:
  timeout: 5m
