linters:
  disable-all: true
  enable:
    - govet
    - vet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - misspell
#
#issues:
#  exclude-rules:
#    - path: _test\.go
#      linters:
#        - goerr113
#        - gochecknoglobals
#        - wsl
#        - lll
#        - funlen

run:
  timeout: 5m
