---
name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }} - 1.22
    strategy:
      matrix:
        dir: [., ./store/awsrds, ./store/vault]
        include:
          - dir: .
            name: go-db-credential-refresh
          - dir: ./store/awsrds
            name: store/awsrds
          - dir: ./store/vault
            name: store/vault
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ${{ matrix.dir }}/go.sum
      - name: Build
        run: go build -mod=readonly -v ./...
        working-directory: ${{ matrix.dir }}
