name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }} - ${{ matrix.go }}
    strategy:
      matrix:
        go: ["1.19.x", "1.20.x"]
        dir: [".", "./store/awsrds", "./store/vault"]
        include:
          - dir: "."
            name: "go-db-credential-refresh"
          - dir: "./store/awsrds"
            name: "store/awsrds"
          - dir: "./store/vault"
            name: "store/vault"
    steps:
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        id: go
      - uses: actions/checkout@v3
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ matrix.dir }}-${{ hashFiles('**/go.sum') }}
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ matrix.dir }}-${{ hashFiles('**/go.sum') }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.dir }}
